---

- name: Write systemd service file
  template:
    src: fibonacci.service.j2
    dest: /etc/systemd/system/fibonacci.service

- name: Reload systemd
  command: systemctl daemon-reload

- name: Enable systemd service
  command: systemctl enable fibonacci

- name: Start systemd service
  command: systemctl start fibonacci
  when: "{{ start_service }}"